package com.bussiness.slodoggiesapp.navigation

object Routes {
    //Business Provider
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val JOIN_THE_PACK = "joinThePack"
    const val PHONE_AUTH_SCREEN = "phoneAuth"
    const val EMAIL_AUTH_SCREEN = "emailAuth"
    const val VERIFY_OTP = "verifyOTP/{type}"
    const val BUSINESS_REGISTRATION = "businessRegistration"
    const val ADD_SERVICE = "addServices"
    const val HOME_SCREEN = "home"
    const val DISCOVER_SCREEN = "discover"
    const val SERVICES_SCREEN = "services"
    const val MAIN_SCREEN = "MainScreen"
    const val PERSON_DETAIL_SCREEN = "PersonDetail"
    const val PROFILE_SCREEN = "Profile"
    const val FOLLOWER_SCREEN = "FollowerScreen"
    const val SPONSORED_ADS_SCREEN = "SponsoredAds"
    const val EDIT_PROFILE_SCREEN = "EditProfile"
    const val POST_SCREEN = "PostScreen"
    const val EDIT_BUSINESS_SCREEN = "EditBusiness"
    const val SETTINGS_SCREEN = "SettingsScreen"
    const val SAVED_ITEM_SCREEN = "SavedItem"
    const val ABOUT_US_SCREEN = "AboutUs"
    const val TERMS_AND_CONDITION_SCREEN = "TermsAndCondition"
    const val PRIVACY_POLICY_SCREEN = "PrivacyPolicy"
    const val FAQ_SCREEN = "FAQ"
    const val HELP_AND_SUPPORT_SCREEN = "HelpAndSupport"
    const val MY_EVENT_SCREEN = "MyEvent"

    //Common
    const val NOTIFICATION_PERMISSION_SCREEN = "notificationAlert"
    const val LOCATION_PERMISSION_SCREEN= "locationAlert"
    //Pet Owner
    const val PET_HOME_SCREEN = "petHomeScreen"
    const val PET_DISCOVER_SCREEN = "petDiscoverScreen"
    const val PET_POST_SCREEN = "petPostScreen"
    const val PET_SERVICES_SCREEN = "petServicesScreen"
    const val PET_PROFILE_SCREEN = "petProfileScreen"
    const val PET_MAIN_SCREEN = "PetMainScreen"
    const val SERVICE_PROVIDER_DETAILS = "serviceProviderDetails"
    const val PROFILE_FOLLOWER_FOLLOWING = "ProfileFollowerAndFollowingScreen"
    const val EDIT_PET_PROFILE_SCREEN = "EditPetProfileScreen"
    const val PET_EDIT_PROFILE_SCREEN = "PetEditProfileScreen"
    const val PET_SETTINGS_SCREEN = "PetSettingsScreen"
    const val PET_SAVED_SCREEN = "PetSavedScreen"
    const val PET_MY_EVENTS_SCREEN = "PetMyEventsScreen"
    const val PET_GROOMING_CHAT_SCREEN = "PetGroomingChatScreen"
    const val PET_EVENT_COMMUNITY_SCREEN = "EventCommunityScreen"
    const val PET_ADD_PARTICIPANTS_SCREEN = "PetAddParticipantsScreen"
}
